config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
 
  get '/categories' => 'categories#index'
  get '/categories/new' => 'categories#new', as: 'new_category'
  post '/categories' => 'categories#create', as: 'create_category'
  get '/categories/:id' => 'categories#show', as: 'category'
  get '/categories/:id/edit' => 'categories#edit', as: 'edit_category'
  patch '/categories/:id' => 'categories#update'
  delete 'categories/:id' => 'categories#destroy'

  get '/bahay' => 'bahay#index'

  get '/tasks/new' => 'tasks#new', as: 'new_task'
  get '/tasks/:id' => 'tasks#show', as: 'task'

  # root "categories#index"

  # get '/categories' => 'categories#index'
  # get '/categories/new' => 'categories#new', as: 'new_category'
  # post '/categories' => 'categories#create', as: 'create_category'
  # get '/categories/:id' => 'categories#show', as: 'category'
  # get '/categories/:id/edit' => 'categories#edit', as: 'edit_category'
  # patch '/categories/:id' => 'categories#update'
  # delete '/categories/:id' => 'categories#destroy', as: 'delete_category'




  # get "/articles", to: "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
    has_many :tasks
  # scope :by_user, lambda { |user| where(:user_id => user.id) }
  scope :by_user, lambda { |user| 
        where(:user_id => user.id)
    }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # enum role: [:user, :moderator, :admin]
  # after_initialize :set_default_role, :if => :new_record?

  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/bahay_controller.rb
class BahayController < ApplicationController
  def index
    @categories = Category.by_user(current_user).pluck(:id)
    @tasks = Task.includes(:category).where(category_id: @categories)
    @task_id = Task.includes(:category).where(category_id: @categories).pluck(:category_id)
    @categories_tasks = Category.find(@task_id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.by_user(current_user)
  end

  def show
    @categories = Category.by_user(current_user).pluck(:id)
    @tasks = Task.includes(:category).where(category_id: @categories)
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)

    @category.user = current_user
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def set_category
    @category = Category.by_user(current_user).find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @categories = Category.by_user(current_user).pluck(:id)
    @tasks = Task.includes(:category).where(category_id: @categories)
    @task_id = Task.includes(:category).where(category_id: @categories).pluck(:category_id)
    @categories_tasks = Category.find(@task_id)
  end

  def new
    @task = Task.new
  end

  private
  def set_category
    @category = Category.by_user(current_user).find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end 

  def set_task
    @tasks = Task.includes(:category).where(category_id: @categories)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bahay/index.html.erb
<nav class="nav-bar">
  <ul>
    <li><%= link_to "Categories Page", categories_path %></li>
  </ul>
</nav>

<p><%= @categories.inspect %></p>
<br/>
<p><%= @tasks.inspect %></p>
<br/>
<p><%= @task_id.inspect %></p>
<br/>
<p><%= @categories_tasks.inspect %></p>
<br/>
<h5>~Real View begins here~</h5>

<div>
  <% @tasks.each do |task| %>
      <% @categories_tasks.each do |categ|%>
          <% if categ.id == task.category_id %>
          <ul>
              <li>Task Name: <%= task.name %></li>
              <li>Task Body: <%= task.body %></li>
              <li>Belongs to Category: <%=link_to categ.name, categ, class:"text-dark text-decoration-none link-primary fw-bold text-uppercase" %></li>
              <%#<li>(Under Construction)
              <%#<%= button_to "Delete", task_path(task.id) , method: :delete, class:"btn btn-danger d-inline-block mb-1", style:"width: 35%; font-size: 12px;"%>
              <%#<%= link_to "Edit", edit_task_path(task.id), class:"btn btn-danger d-inline-block mb-1", style:"width: 35%; font-size: 12px;" %>
              <%#<%= link_to "View", task_path(task.id), class:"btn btn-danger d-block ", style:"width: 35%; font-size: 12px;" %>
              <%#</li> %>
          </ul>
          <% else %>
        
          <% end %>
      <% end %>
  <% end %>
  
</div>

<p>~End of this Page~</p>

app/views/categories/_form.html.erb
<%= form_with(model:category) do |form| %>
  <div>
    <%= form.label :name %> <%# style: "display: block; font-weight:bold; text-transform: uppercase;" %>
    <%= form.text_field :name %>
  </div>
  <br/>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= button_to link_to "Back", categories_path %>

app/views/categories/edit.html.erb
<h1 class="page_title">'Edit the Category' Page!</h1>
<h3>Currently editing Category: <%= @category.name%></h3>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<nav class="nav-bar">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Bahay", bahay_path %></li>
  </ul>
</nav>

<body class="bodyThing">
  <h1 class="page_title">The Categories Page</h1>

  <ul>
    <% @categories.each do |category|%>
      <li>
        <a href="<%= category_path(category) %>">
          <%= category.name %>
        </a>
      </li>
    <% end %>
  </ul>

  <br/>
  <%= button_to link_to "New Category", new_category_path %>
</body>

app/views/categories/new.html.erb
<h1 class="page_title">Bagong Categorya</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<nav class="nav-bar">
  <ul>
    <li><%= link_to "Categories Page", categories_path %></li>
  </ul>
</nav>

<body>
  <h1 class="page_title">We're in /categories/show</h1>

  <p>Currently showing Category: </p>
  <span><%= @category.inspect %></span>

  <p>Category Title: <strong><%= @category.name%></strong></p>


  <br/>
  <%= button_to link_to "Edit Me", edit_category_path(@category) %>
  <br/>
  <%= button_to "Obliterate this Category", @category, method: :delete %>
  <h4>Tasks related to this Category</h4>
  <% @tasks.each do |task| %>
    <% if @category.id == task.category_id %></li>
      <ul>
        <li>Task Name:
          <a href="<%= task_path(task) %>">
            <%= task.name %>
          </a>
        </li>
      </ul>
    <% end %>
  <% end %>
  <%= button_to link_to "New Task", new_task_path %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<nav class="nav-bar">
  <ul>
    <li><%= link_to "The Categories", categories_path %></li>
  </ul>
</nav>

<% if current_user %>
  <p>'Sup <%= current_user.email %>!</p>
  <p>You are a [<%= current_user.role %>]</p>
  <p>
    Successfully authenticated with a Devise account.
    The application is now ready for interaction!
  </p>
  
  <br>
  <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
  
<% else %>
  <p>You ain't signed in.</p>
  <%= link_to "Sign Up!", new_user_registration_path %>
  <br />
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model:task) do |form| %>
  <div>
    <%= form.label :name %> <%# style: "display: block; font-weight:bold; text-transform: uppercase;" %>
    <%= form.text_field :name %>
  </div>
  <br/>
  <div>
    <%= form.label :body %> <%# style: "display: block; font-weight:bold; text-transform: uppercase;" %>
    <%= form.text_field :body %>
  </div>
  <br/>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= button_to link_to "Back", categories_path %>

app/views/tasks/new.html.erb
<h1 class="page_title">A New Task Has Awoken</h1>

<%= render 'form', category: @category %>

app/views/tasks/show.html.erb
<nav class="nav-bar">
  <ul>
    <li><%= link_to "Back to Categories", categories_path %></li>
  </ul>
</nav>

<body>

  
</body>